### ISSUE TITLE
Bug in src/onion-spi.c

### ISSUE THREAD

**Issue by GaryBoone** [OnionIoT/spi-gpio-driver#2]
In src/onion-spi.c, at line 189:

    if (res < 1) {
			// send failed
			onionPrint(ONION_SEVERITY_FATAL, "ERROR: SPI transfer failed\n");
			*rxBuffer 	= 0;
			status	== EXIT_FAILURE;
		}

Should be 

    status	= EXIT_FAILURE;

**Comment by greenbreakfast** [comment]
fixed! will release an updated package soon!
