### ISSUE TITLE
spiTransfer() only transmits 16 bytes at maximum

### ISSUE THREAD

**Issue by gamer-cndg** [OnionIoT/spi-gpio-driver#3]
I'm currently working on a SPI display driver and I have hit a roadblock with your SPI implementation. In my case, I'd like to transmit my whole framebuffer (`176*220*2` bytes) at once. 

However, once I go over 16 bytes of length in the `spiTransfer()` function, the  function just returns an error.
 
```
[+] Trying to write length 16.
onion-spi:: Trasferring 0xff, 16 bytes
   Received: 0x00, ioctl status: 16
[+] Write 16 bytes okay
[+] Trying to write length 17.
onion-spi:: Trasferring 0xff, 17 bytes
ERROR: SPI transfer failed
```

Test code:

```c
	//test max size
	int err = EXIT_SUCCESS;
	int len = 1;
        static uint8_t dummyRXBuf[176*220*2];
	while(err == EXIT_SUCCESS) {
		printf("[+] Trying to write length %d.\n", len);
		uint8_t* testBuf = malloc(len);
		memset(testBuf, 0xff, len);
		err = spiTransfer(&params, testBuf, dummyRXBuf, len);
		if(err == EXIT_SUCCESS) {
			printf("[+] Write %d bytes okay\n", len);
			len++;
		}
		free(testBuf);
	}
```

SPI params initialization:

```c
	spiParamInit(&params);
	params.mosiGpio = initParams->mosi;
	params.sckGpio = initParams->sclk;
	params.csGpio = initParams->cs;
	params.speedInHz = initParams->speedInHz; //20 mhz
	params.modeBits = SPI_MODE_0; //only SPIMODE_0, no dual TX or RX as "default"..
	params.busNum = 1; //this comes from my local machine. no idea if it works elsewhere.. (ls /dev/spi*)
	params.deviceId = 32766;
```

All I can see in (https://github.com/OnionIoT/spi-gpio-driver/blob/master/src/onion-spi.c#L182) is a call to `ioctl`, so I think the fault must be with the kernel module. 

Can you please correct this error? With your implementation, transmitting in blocks of 16 bytes with a bit-banged driver yields a display FPS of about 2.5 FPS. Also, what's the maximum speed with this implementation? Is this implementation backed by DMA?

**Comment by greenbreakfast** [comment]
For reference: SPI transfer issues on the Omega2 have been fixed since firmware version 0.2.0 
More details here: https://onion.io/2bt-brand-new-os-release/

Closing this issue since this repo is deprecated. See this [technical FAQ on bitbanging SPI](https://community.onion.io/topic/4500/faq-how-can-i-make-a-software-based-bit-bang-spi-bus-i-need-2-spi-devices-can-i-use-any-4-gpios-as-an-spi-bus) instead.
