### ISSUE TITLE
Device registering on Kernel 4.14.81 not working

### ISSUE THREAD

**Issue by Simon-87** [OnionIoT/spi-gpio-driver#6]
I am trying to get the bit-bang SPI working on kernel 4.14.81
But it isnt working.
The generated insmod command is: "insmod spi-gpio-custom bus0=1,15,16,17,0,100000,11"
and dmesg says:
[ 1099.183736] Custom GPIO-based SPI driver version 0.1
[ 1099.190789] spi_gpio spi_gpio.1: can't setup spi1.0, status -16
[ 1099.196893] spi-gpio-custom: unable to create slave 0 for bus 1

**Comment by greenbreakfast** [comment]
@Simon-87 this repo (and utility) is deprecated

Please see this FAQ post instead: https://community.onion.io/topic/4500/faq-how-can-i-make-a-software-based-bit-bang-spi-bus-i-need-2-spi-devices-can-i-use-any-4-gpios-as-an-spi-bus
